apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/nabeelp/k8s-gitops-argo.git
      revision: main
      files:
      - path: cluster/**/helm-config.json
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        name: ''
        namespace: '{{path.basename}}'
        server: https://kubernetes.default.svc
      source:
        chart: '{{chartName}}'
        path: ''
        repoURL: '{{chartRepo}}'
        targetRevision: '{{chartVersion}}'
        helm:
          valueFiles:
          - values.yaml
      project: default
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply={{serverSideApply}}
