kind: Deployment
apiVersion: apps/v1
metadata:
  name: inspector-gadget
  labels:
    app: inspector-gadget

spec:
  replicas: 1
  selector:
    matchLabels:
      app: inspector-gadget
  template:
    metadata:
      labels:
        app: inspector-gadget
    spec:
      containers:
        - name: inspector-gadget
          image: jelledruyts/inspectorgadget:latest
          ports:
            - name: web
              containerPort: 80
          env:
            - name: PathBase
              value: /inspector-gadget/
---
apiVersion: v1
kind: Service
metadata:
  name: inspector-gadget

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: inspector-gadget
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inspector-gadget-ingress
spec:
  rules:
  - http:
      paths:
      - path: /inspector-gadget/
        pathType: Prefix
        backend:
          service:
            name: inspector-gadget
            port:
              name: web
