# Custom values for argo-cd - defaults: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

## Argo Configs
configs:
  # Argo CD configuration parameters
  ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml
  params:
    ## Server properties
    # -- Run server without TLS
    server.insecure: true

## Dex
dex:
  # -- Enable dex
  enabled: false

## Notifications controller
notifications:
  # -- Enable notifications controller
  enabled: false
